### ISSUE TITLE
[Important] Change window structure (ListManager)

### ISSUE THREAD

**Issue by ThibautSF** [ThibautSF/ParadoxosModManager#5]
Like i do for the ListCreator window, migrate the ListManager widow structure from BorderPane to GridPane before adding new content in this window.

The GridPane object have a better responsive and resize logic and make more complex window structure much easier to create and design.

**Comment by ThibautSF** [comment]
WIP

![image](https://cloud.githubusercontent.com/assets/9386581/25148053/e0dd18c0-2479-11e7-9a15-df5399b96b49.png)

**Comment by ThibautSF** [comment]
I push a stable work.

But there is still a bug with resize of lists (height) for both list management and list creator windows.

**Comment by NicolasGrosjean** [comment]
How have you pushed this? Directly on github? By using a desktop application like GitHub Desktop?
Because my commits have disappeared, it is very strange

**Comment by ThibautSF** [comment]
What ? Oo I push ListManager but before i do any change i download the updated file with your modifications... A bug in EGit...

**Comment by ThibautSF** [comment]
It should be corrected.

**Comment by NicolasGrosjean** [comment]
When I have synchronized GitHub Desktop (it makes a pull and push), it has reintroduced my changes.

I think that in fact, they have not disappeared with a bug with Egit.
The development branches are the following.
![image](https://cloud.githubusercontent.com/assets/13560473/25302423/f30510b8-273d-11e7-9b26-c9699bd21ac9.png)
When you push, we see only your branch (the blue one) because the branch (in fact it is a pointer on a commit) was on your branch and you have not merged my branch.
When you pull, you fetch (get all the commits from the remote repository) and you merge your local branch to yours.

**To conclude**
- Use only git for file management. When I say git, I include any application which is based on git. So Egit is good. What I mean is, you don't need and you mustn't download files from GitHub.
- Before pushing, do pulling. Normally, git (so Egit) would forgive to push before pulling.
