### ISSUE TITLE
Error: Could not find or load main class application.ModManager

### ISSUE THREAD

**Issue by cpeosphoros** [ThibautSF/ParadoxosModManager#59]
```
./LaunchUnix.sh
Error: Could not find or load main class application.ModManager
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application

```

Using Linux Mint Tina 19.2 with both openjdk and openjfx installed

**Comment by meganomic** [comment]
I had the same issue and found out you have to type this. Modify to whatever path you have java in.

`/usr/lib/jvm/java-13-openjdk/bin/java --module-path /usr/lib/jvm/java-13-openjdk/lib/javafx.base.jar:/usr/lib/jvm/java-13-openjdk/lib/javafx.controls.jar:/usr/lib/jvm/java-13-openjdk/lib/javafx.fxml.jar:/usr/lib/jvm/java-13-openjdk/lib/javafx.graphics.jar:/usr/lib/jvm/java-13-openjdk/lib/javafx.media.jar:/usr/lib/jvm/java-13-openjdk/lib/javafx.swing.jar:/usr/lib/jvm/java-13-openjdk/lib/javafx.web.jar:/usr/lib/jvm/java-13-openjdk/lib/javafx-swt.jar:/usr/lib/jvm/java-13-openjfx/lib/javafx.base.jar:/usr/lib/jvm/java-13-openjfx/lib/javafx.controls.jar:/usr/lib/jvm/java-13-openjfx/lib/javafx.fxml.jar:/usr/lib/jvm/java-13-openjfx/lib/javafx.graphics.jar:/usr/lib/jvm/java-13-openjfx/lib/javafx.media.jar:/usr/lib/jvm/java-13-openjfx/lib/javafx.swing.jar:/usr/lib/jvm/java-13-openjfx/lib/javafx.web.jar:/usr/lib/jvm/java-13-openjfx/lib/javafx-swt.jar --add-modules ALL-MODULE-PATH -jar ParadoxosModManager.jar`

Sadly it still doesn't work. But it gives a new error which is nice I guess.

`Can't find bundle for base name com.sun.javafx.tk.quantum.QuantumMessagesBundle`

**Comment by ThibautSF** [comment]
Hi,

PMM is only compatible with Java 8 and the JavaFX for java 8. There is no problem on Windows since Oracle still give java installers.

But for unix system, it appears (at least with ubuntu) that openjdk 8 don't include javafx, and when you want to add the javafx package for openjdk 8 it's empty. (My main dev computer beeing on XUbuntu i can't update easily this PMM anymore)

I'm working on a Java 11+ port here : https://github.com/ThibautSF/ParadoxosModManagerRework
(for now openjdk 11 and openjfx 11 and maven)
The app is buildable and should work at minimal.

**Comment by meganomic** [comment]
I installed OpenJDK 8 and OpenJFX 8 on Arch and it's working fine now. Guess I was just being an idiot for not instantly installing version 8. Oh well. Live and learn. I figured it would be fine since it says "Java 8u40 (at least)". 13 is at least :D

**Comment by ThibautSF** [comment]
Repository discontinued

Please re-open in the new repository if needed
https://github.com/ThibautSF/ParadoxosModManager
